import prisma from '../config/prismaClient.js';
import { Prisma } from '@prisma/client';

interface ProjectData {
  title: string;
  description?: string;
  assets?: any[];
  data?: any; // JSON (timeline u otros datos)
}

interface TimelineClip {
  id: string;
  assetId: number;
  start: number;
  end: number;
}

interface TimelineTrack {
  id: string;
  type: 'video' | 'audio' | 'text';
  clips: TimelineClip[];
}

interface TimelineData {
  tracks: TimelineTrack[];
}

// Helper: asegura que data tenga forma de TimelineData
function ensureTimeline(data: unknown): TimelineData {
  const d = (data ?? {}) as any;
  if (d && typeof d === 'object' && Array.isArray(d.tracks)) {
    return d as TimelineData;
  }
  return { tracks: [] };
}

class EditorService {
  // Crear proyecto vacío o con datos iniciales
  async createProject(userId: number, data: ProjectData) {
    return prisma.project.create({
      data: {
        ...data,
        userId,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    });
  }

  // Crear proyecto a partir de draft generado por el Agente
  async createProjectFromAgent(userId: number, draft: ProjectData) {
    return this.createProject(userId, {
      ...draft,
      description: draft.description || 'Generated by Marketing AI Agent',
    });
  }

  // Listar proyectos con filtros opcionales
  async listProjects(
    userId: number,
    filters?: { createdAfter?: Date; createdBefore?: Date }
  ) {
    const createdAt =
      filters?.createdAfter || filters?.createdBefore
        ? {
            ...(filters?.createdAfter ? { gte: filters.createdAfter } : {}),
            ...(filters?.createdBefore ? { lte: filters.createdBefore } : {}),
          }
        : undefined;

    return prisma.project.findMany({
      where: { userId, ...(createdAt ? { createdAt } : {}) },
      orderBy: { createdAt: 'desc' },
    });
  }

  // Obtener proyecto por id (del usuario)
  async getProjectById(userId: number, projectId: number) {
    return prisma.project.findFirst({
      where: { id: projectId, userId },
    });
  }

  // Actualizar proyecto completo
  async updateProject(
    userId: number,
    projectId: number,
    data: Partial<ProjectData>
  ) {
    const project = await this.getProjectById(userId, projectId);
    if (!project) return null;

    return prisma.project.update({
      where: { id: projectId },
      data: { ...data, updatedAt: new Date() },
    });
  }

  // === TIMELINE ===

  // Añadir clip a un track existente
  async addClipToTimeline(
    userId: number,
    projectId: number,
    trackId: string,
    clip: TimelineClip
  ) {
    const project = await this.getProjectById(userId, projectId);
    if (!project) return null;

    const timeline = ensureTimeline(project.data);
    const track = timeline.tracks.find((t) => t.id === trackId);
    if (!track) return null; // no inventamos tracks

    track.clips.push(clip);

    return prisma.project.update({
      where: { id: projectId },
      data: {
        data: (timeline as unknown) as Prisma.InputJsonValue, // ✅ casteo JSON
        updatedAt: new Date(),
      },
    });
  }

  // Mover clip (cambiar start conservando duración)
  async moveClip(
    userId: number,
    projectId: number,
    clipId: string,
    newStart: number
  ) {
    const project = await this.getProjectById(userId, projectId);
    if (!project) return null;

    const timeline = ensureTimeline(project.data);
    for (const track of timeline.tracks) {
      const clip = track.clips.find((c) => c.id === clipId);
      if (clip) {
        const duration = clip.end - clip.start;
        clip.start = newStart;
        clip.end = newStart + duration;
        break;
      }
    }

    return prisma.project.update({
      where: { id: projectId },
      data: {
        data: (timeline as unknown) as Prisma.InputJsonValue, // ✅ casteo JSON
        updatedAt: new Date(),
      },
    });
  }

  // Remover clip
  async removeClip(userId: number, projectId: number, clipId: string) {
    const project = await this.getProjectById(userId, projectId);
    if (!project) return null;

    const timeline = ensureTimeline(project.data);
    timeline.tracks.forEach((track) => {
      track.clips = track.clips.filter((c) => c.id !== clipId);
    });

    return prisma.project.update({
      where: { id: projectId },
      data: {
        data: (timeline as unknown) as Prisma.InputJsonValue, // ✅ casteo JSON
        updatedAt: new Date(),
      },
    });
  }

  // === CRUD Proyectos / Assets / Stats / Audio ===

  // Borrar proyecto
  async deleteProject(userId: number, projectId: number) {
    return prisma.project.deleteMany({ where: { id: projectId, userId } });
  }

  // Duplicar proyecto
  async duplicateProject(userId: number, projectId: number) {
    const project = await this.getProjectById(userId, projectId);
    if (!project) return null;

    const { id, createdAt, updatedAt, ...rest } = project;

    return prisma.project.create({
      data: {
        ...rest,
        userId,
        title: `${rest.title} (Copy)`,
        data: (rest.data as unknown) as Prisma.InputJsonValue,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    });
  }

  // Assets
  async listAssets(userId: number) {
    return prisma.asset.findMany({ where: { userId } });
  }

  async addAsset(userId: number, data: any) {
    return prisma.asset.create({
      data: { ...data, userId, createdAt: new Date() },
    });
  }

  async deleteAsset(userId: number, assetId: number) {
    return prisma.asset.deleteMany({ where: { id: assetId, userId } });
  }

  // Stats
  async getEditorStats(userId: number) {
    const projectCount = await prisma.project.count({ where: { userId } });
    const assetCount = await prisma.asset.count({ where: { userId } });
    return { projectCount, assetCount };
  }

  // Audio
  async regenerateVoice(
    userId: number,
    projectId: number,
    text: string,
    voice: string
  ) {
    const project = await this.getProjectById(userId, projectId);
    if (!project) return null;

    const current = (project.data ?? {}) as any;
    const next = {
      ...current,
      regeneratedVoice: { text, voice, date: new Date() },
    };

    return prisma.project.update({
      where: { id: projectId },
      data: {
        data: (next as unknown) as Prisma.InputJsonValue, // ✅ casteo JSON
        updatedAt: new Date(),
      },
    });
  }

  async updateAudioMix(userId: number, projectId: number, data: any) {
    const project = await this.getProjectById(userId, projectId);
    if (!project) return null;

    const current = (project.data ?? {}) as any;
    const next = { ...current, ...data, updatedAt: new Date() };

    return prisma.project.update({
      where: { id: projectId },
      data: {
        data: (next as unknown) as Prisma.InputJsonValue, // ✅ casteo JSON
        updatedAt: new Date(),
      },
    });
  }

  async addSoundEffect(userId: number, projectId: number, data: any) {
    const project = await this.getProjectById(userId, projectId);
    if (!project) return null;

    const current = (project.data ?? {}) as any;
    const next = { ...current, ...data, addedSfxAt: new Date() };

    return prisma.project.update({
      where: { id: projectId },
      data: {
        data: (next as unknown) as Prisma.InputJsonValue, // ✅ casteo JSON
        updatedAt: new Date(),
      },
    });
  }
}

export default new EditorService();
